/* This file was generated by SableCC (http://www.sablecc.org/). */

package lParser.node;

import lParser.analysis.*;

@SuppressWarnings("nls")
public final class AInfExpression3 extends PExpression3
{
    private PExpression3 _expression3_;
    private TInf _inf_;
    private PExpression4 _expression4_;

    public AInfExpression3()
    {
        // Constructor
    }

    public AInfExpression3(
        @SuppressWarnings("hiding") PExpression3 _expression3_,
        @SuppressWarnings("hiding") TInf _inf_,
        @SuppressWarnings("hiding") PExpression4 _expression4_)
    {
        // Constructor
        setExpression3(_expression3_);

        setInf(_inf_);

        setExpression4(_expression4_);

    }

    @Override
    public Object clone()
    {
        return new AInfExpression3(
            cloneNode(this._expression3_),
            cloneNode(this._inf_),
            cloneNode(this._expression4_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAInfExpression3(this);
    }

    public PExpression3 getExpression3()
    {
        return this._expression3_;
    }

    public void setExpression3(PExpression3 node)
    {
        if(this._expression3_ != null)
        {
            this._expression3_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expression3_ = node;
    }

    public TInf getInf()
    {
        return this._inf_;
    }

    public void setInf(TInf node)
    {
        if(this._inf_ != null)
        {
            this._inf_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._inf_ = node;
    }

    public PExpression4 getExpression4()
    {
        return this._expression4_;
    }

    public void setExpression4(PExpression4 node)
    {
        if(this._expression4_ != null)
        {
            this._expression4_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expression4_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expression3_)
            + toString(this._inf_)
            + toString(this._expression4_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expression3_ == child)
        {
            this._expression3_ = null;
            return;
        }

        if(this._inf_ == child)
        {
            this._inf_ = null;
            return;
        }

        if(this._expression4_ == child)
        {
            this._expression4_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expression3_ == oldChild)
        {
            setExpression3((PExpression3) newChild);
            return;
        }

        if(this._inf_ == oldChild)
        {
            setInf((TInf) newChild);
            return;
        }

        if(this._expression4_ == oldChild)
        {
            setExpression4((PExpression4) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
