/* This file was generated by SableCC (http://www.sablecc.org/). */

package lParser.node;

import lParser.analysis.*;

@SuppressWarnings("nls")
public final class ASinonInstruction extends PInstruction
{
    private TSi _si_;
    private PExpression _expression_;
    private TAlors _alors_;
    private PBlocInstructions _blocSi_;
    private TSinon _sinon_;
    private PBlocInstructions _blocSinon_;

    public ASinonInstruction()
    {
        // Constructor
    }

    public ASinonInstruction(
        @SuppressWarnings("hiding") TSi _si_,
        @SuppressWarnings("hiding") PExpression _expression_,
        @SuppressWarnings("hiding") TAlors _alors_,
        @SuppressWarnings("hiding") PBlocInstructions _blocSi_,
        @SuppressWarnings("hiding") TSinon _sinon_,
        @SuppressWarnings("hiding") PBlocInstructions _blocSinon_)
    {
        // Constructor
        setSi(_si_);

        setExpression(_expression_);

        setAlors(_alors_);

        setBlocSi(_blocSi_);

        setSinon(_sinon_);

        setBlocSinon(_blocSinon_);

    }

    @Override
    public Object clone()
    {
        return new ASinonInstruction(
            cloneNode(this._si_),
            cloneNode(this._expression_),
            cloneNode(this._alors_),
            cloneNode(this._blocSi_),
            cloneNode(this._sinon_),
            cloneNode(this._blocSinon_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASinonInstruction(this);
    }

    public TSi getSi()
    {
        return this._si_;
    }

    public void setSi(TSi node)
    {
        if(this._si_ != null)
        {
            this._si_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._si_ = node;
    }

    public PExpression getExpression()
    {
        return this._expression_;
    }

    public void setExpression(PExpression node)
    {
        if(this._expression_ != null)
        {
            this._expression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expression_ = node;
    }

    public TAlors getAlors()
    {
        return this._alors_;
    }

    public void setAlors(TAlors node)
    {
        if(this._alors_ != null)
        {
            this._alors_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._alors_ = node;
    }

    public PBlocInstructions getBlocSi()
    {
        return this._blocSi_;
    }

    public void setBlocSi(PBlocInstructions node)
    {
        if(this._blocSi_ != null)
        {
            this._blocSi_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._blocSi_ = node;
    }

    public TSinon getSinon()
    {
        return this._sinon_;
    }

    public void setSinon(TSinon node)
    {
        if(this._sinon_ != null)
        {
            this._sinon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._sinon_ = node;
    }

    public PBlocInstructions getBlocSinon()
    {
        return this._blocSinon_;
    }

    public void setBlocSinon(PBlocInstructions node)
    {
        if(this._blocSinon_ != null)
        {
            this._blocSinon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._blocSinon_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._si_)
            + toString(this._expression_)
            + toString(this._alors_)
            + toString(this._blocSi_)
            + toString(this._sinon_)
            + toString(this._blocSinon_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._si_ == child)
        {
            this._si_ = null;
            return;
        }

        if(this._expression_ == child)
        {
            this._expression_ = null;
            return;
        }

        if(this._alors_ == child)
        {
            this._alors_ = null;
            return;
        }

        if(this._blocSi_ == child)
        {
            this._blocSi_ = null;
            return;
        }

        if(this._sinon_ == child)
        {
            this._sinon_ = null;
            return;
        }

        if(this._blocSinon_ == child)
        {
            this._blocSinon_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._si_ == oldChild)
        {
            setSi((TSi) newChild);
            return;
        }

        if(this._expression_ == oldChild)
        {
            setExpression((PExpression) newChild);
            return;
        }

        if(this._alors_ == oldChild)
        {
            setAlors((TAlors) newChild);
            return;
        }

        if(this._blocSi_ == oldChild)
        {
            setBlocSi((PBlocInstructions) newChild);
            return;
        }

        if(this._sinon_ == oldChild)
        {
            setSinon((TSinon) newChild);
            return;
        }

        if(this._blocSinon_ == oldChild)
        {
            setBlocSinon((PBlocInstructions) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
