/* This file was generated by SableCC (http://www.sablecc.org/). */

package lParser.node;

import lParser.analysis.*;

@SuppressWarnings("nls")
public final class AVariableListDeclarationVariable extends PListDeclarationVariable
{
    private PDeclarVar _declarVar_;
    private PListDeclarationVariableNext _listDeclarationVariableNext_;

    public AVariableListDeclarationVariable()
    {
        // Constructor
    }

    public AVariableListDeclarationVariable(
        @SuppressWarnings("hiding") PDeclarVar _declarVar_,
        @SuppressWarnings("hiding") PListDeclarationVariableNext _listDeclarationVariableNext_)
    {
        // Constructor
        setDeclarVar(_declarVar_);

        setListDeclarationVariableNext(_listDeclarationVariableNext_);

    }

    @Override
    public Object clone()
    {
        return new AVariableListDeclarationVariable(
            cloneNode(this._declarVar_),
            cloneNode(this._listDeclarationVariableNext_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVariableListDeclarationVariable(this);
    }

    public PDeclarVar getDeclarVar()
    {
        return this._declarVar_;
    }

    public void setDeclarVar(PDeclarVar node)
    {
        if(this._declarVar_ != null)
        {
            this._declarVar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._declarVar_ = node;
    }

    public PListDeclarationVariableNext getListDeclarationVariableNext()
    {
        return this._listDeclarationVariableNext_;
    }

    public void setListDeclarationVariableNext(PListDeclarationVariableNext node)
    {
        if(this._listDeclarationVariableNext_ != null)
        {
            this._listDeclarationVariableNext_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listDeclarationVariableNext_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._declarVar_)
            + toString(this._listDeclarationVariableNext_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._declarVar_ == child)
        {
            this._declarVar_ = null;
            return;
        }

        if(this._listDeclarationVariableNext_ == child)
        {
            this._listDeclarationVariableNext_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._declarVar_ == oldChild)
        {
            setDeclarVar((PDeclarVar) newChild);
            return;
        }

        if(this._listDeclarationVariableNext_ == oldChild)
        {
            setListDeclarationVariableNext((PListDeclarationVariableNext) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
