/* This file was generated by SableCC (http://www.sablecc.org/). */

package lParser.node;

import lParser.analysis.*;

@SuppressWarnings("nls")
public final class AVideListDeclarationVariable extends PListDeclarationVariable
{

    public AVideListDeclarationVariable()
    {
        // Constructor
    }

    @Override
    public Object clone()
    {
        return new AVideListDeclarationVariable();
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVideListDeclarationVariable(this);
    }

    @Override
    public String toString()
    {
        return "";
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        throw new RuntimeException("Not a child.");
    }
}
