/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AAddTerm extends PAddTerm
{
    private PAddition _addition_;
    private PTerm _term_;

    public AAddTerm()
    {
        // Constructor
    }

    public AAddTerm(
        @SuppressWarnings("hiding") PAddition _addition_,
        @SuppressWarnings("hiding") PTerm _term_)
    {
        // Constructor
        setAddition(_addition_);

        setTerm(_term_);

    }

    @Override
    public Object clone()
    {
        return new AAddTerm(
            cloneNode(this._addition_),
            cloneNode(this._term_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAddTerm(this);
    }

    public PAddition getAddition()
    {
        return this._addition_;
    }

    public void setAddition(PAddition node)
    {
        if(this._addition_ != null)
        {
            this._addition_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._addition_ = node;
    }

    public PTerm getTerm()
    {
        return this._term_;
    }

    public void setTerm(PTerm node)
    {
        if(this._term_ != null)
        {
            this._term_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._term_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._addition_)
            + toString(this._term_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._addition_ == child)
        {
            this._addition_ = null;
            return;
        }

        if(this._term_ == child)
        {
            this._term_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._addition_ == oldChild)
        {
            setAddition((PAddition) newChild);
            return;
        }

        if(this._term_ == oldChild)
        {
            setTerm((PTerm) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
