/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import java.util.*;
import analysis.*;

@SuppressWarnings("nls")
public final class AArgumentsExpression extends PArgumentsExpression
{
    private PExpression _expression_;
    private final LinkedList<PArgumentsComma> _argumentsComma_ = new LinkedList<PArgumentsComma>();

    public AArgumentsExpression()
    {
        // Constructor
    }

    public AArgumentsExpression(
        @SuppressWarnings("hiding") PExpression _expression_,
        @SuppressWarnings("hiding") List<?> _argumentsComma_)
    {
        // Constructor
        setExpression(_expression_);

        setArgumentsComma(_argumentsComma_);

    }

    @Override
    public Object clone()
    {
        return new AArgumentsExpression(
            cloneNode(this._expression_),
            cloneList(this._argumentsComma_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAArgumentsExpression(this);
    }

    public PExpression getExpression()
    {
        return this._expression_;
    }

    public void setExpression(PExpression node)
    {
        if(this._expression_ != null)
        {
            this._expression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expression_ = node;
    }

    public LinkedList<PArgumentsComma> getArgumentsComma()
    {
        return this._argumentsComma_;
    }

    public void setArgumentsComma(List<?> list)
    {
        for(PArgumentsComma e : this._argumentsComma_)
        {
            e.parent(null);
        }
        this._argumentsComma_.clear();

        for(Object obj_e : list)
        {
            PArgumentsComma e = (PArgumentsComma) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._argumentsComma_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expression_)
            + toString(this._argumentsComma_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expression_ == child)
        {
            this._expression_ = null;
            return;
        }

        if(this._argumentsComma_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expression_ == oldChild)
        {
            setExpression((PExpression) newChild);
            return;
        }

        for(ListIterator<PArgumentsComma> i = this._argumentsComma_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PArgumentsComma) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
