/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AArguments extends PArguments
{
    private PArgumentsExpression _argumentsExpression_;

    public AArguments()
    {
        // Constructor
    }

    public AArguments(
        @SuppressWarnings("hiding") PArgumentsExpression _argumentsExpression_)
    {
        // Constructor
        setArgumentsExpression(_argumentsExpression_);

    }

    @Override
    public Object clone()
    {
        return new AArguments(
            cloneNode(this._argumentsExpression_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAArguments(this);
    }

    public PArgumentsExpression getArgumentsExpression()
    {
        return this._argumentsExpression_;
    }

    public void setArgumentsExpression(PArgumentsExpression node)
    {
        if(this._argumentsExpression_ != null)
        {
            this._argumentsExpression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._argumentsExpression_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._argumentsExpression_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._argumentsExpression_ == child)
        {
            this._argumentsExpression_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._argumentsExpression_ == oldChild)
        {
            setArgumentsExpression((PArgumentsExpression) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
