/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class ABegin extends PBegin
{
    private PBeginStructure _beginStructure_;
    private TRBrace _rBrace_;

    public ABegin()
    {
        // Constructor
    }

    public ABegin(
        @SuppressWarnings("hiding") PBeginStructure _beginStructure_,
        @SuppressWarnings("hiding") TRBrace _rBrace_)
    {
        // Constructor
        setBeginStructure(_beginStructure_);

        setRBrace(_rBrace_);

    }

    @Override
    public Object clone()
    {
        return new ABegin(
            cloneNode(this._beginStructure_),
            cloneNode(this._rBrace_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABegin(this);
    }

    public PBeginStructure getBeginStructure()
    {
        return this._beginStructure_;
    }

    public void setBeginStructure(PBeginStructure node)
    {
        if(this._beginStructure_ != null)
        {
            this._beginStructure_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._beginStructure_ = node;
    }

    public TRBrace getRBrace()
    {
        return this._rBrace_;
    }

    public void setRBrace(TRBrace node)
    {
        if(this._rBrace_ != null)
        {
            this._rBrace_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rBrace_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._beginStructure_)
            + toString(this._rBrace_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._beginStructure_ == child)
        {
            this._beginStructure_ = null;
            return;
        }

        if(this._rBrace_ == child)
        {
            this._rBrace_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._beginStructure_ == oldChild)
        {
            setBeginStructure((PBeginStructure) newChild);
            return;
        }

        if(this._rBrace_ == oldChild)
        {
            setRBrace((TRBrace) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
