/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AElseBlockMaybe extends PElseBlockMaybe
{
    private PElseBlock _elseBlock_;

    public AElseBlockMaybe()
    {
        // Constructor
    }

    public AElseBlockMaybe(
        @SuppressWarnings("hiding") PElseBlock _elseBlock_)
    {
        // Constructor
        setElseBlock(_elseBlock_);

    }

    @Override
    public Object clone()
    {
        return new AElseBlockMaybe(
            cloneNode(this._elseBlock_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAElseBlockMaybe(this);
    }

    public PElseBlock getElseBlock()
    {
        return this._elseBlock_;
    }

    public void setElseBlock(PElseBlock node)
    {
        if(this._elseBlock_ != null)
        {
            this._elseBlock_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._elseBlock_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._elseBlock_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._elseBlock_ == child)
        {
            this._elseBlock_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._elseBlock_ == oldChild)
        {
            setElseBlock((PElseBlock) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
