/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AExpression extends PExpression
{
    private PSimpleExpression _simpleExpression_;
    private PCompExpr _compExpr_;

    public AExpression()
    {
        // Constructor
    }

    public AExpression(
        @SuppressWarnings("hiding") PSimpleExpression _simpleExpression_,
        @SuppressWarnings("hiding") PCompExpr _compExpr_)
    {
        // Constructor
        setSimpleExpression(_simpleExpression_);

        setCompExpr(_compExpr_);

    }

    @Override
    public Object clone()
    {
        return new AExpression(
            cloneNode(this._simpleExpression_),
            cloneNode(this._compExpr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpression(this);
    }

    public PSimpleExpression getSimpleExpression()
    {
        return this._simpleExpression_;
    }

    public void setSimpleExpression(PSimpleExpression node)
    {
        if(this._simpleExpression_ != null)
        {
            this._simpleExpression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._simpleExpression_ = node;
    }

    public PCompExpr getCompExpr()
    {
        return this._compExpr_;
    }

    public void setCompExpr(PCompExpr node)
    {
        if(this._compExpr_ != null)
        {
            this._compExpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._compExpr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._simpleExpression_)
            + toString(this._compExpr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._simpleExpression_ == child)
        {
            this._simpleExpression_ = null;
            return;
        }

        if(this._compExpr_ == child)
        {
            this._compExpr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._simpleExpression_ == oldChild)
        {
            setSimpleExpression((PSimpleExpression) newChild);
            return;
        }

        if(this._compExpr_ == oldChild)
        {
            setCompExpr((PCompExpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
