/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import java.util.*;
import analysis.*;

@SuppressWarnings("nls")
public final class AParameterParameters extends PParameters
{
    private PParameter _parameter_;
    private final LinkedList<PCommaParameter> _commaParameter_ = new LinkedList<PCommaParameter>();

    public AParameterParameters()
    {
        // Constructor
    }

    public AParameterParameters(
        @SuppressWarnings("hiding") PParameter _parameter_,
        @SuppressWarnings("hiding") List<?> _commaParameter_)
    {
        // Constructor
        setParameter(_parameter_);

        setCommaParameter(_commaParameter_);

    }

    @Override
    public Object clone()
    {
        return new AParameterParameters(
            cloneNode(this._parameter_),
            cloneList(this._commaParameter_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAParameterParameters(this);
    }

    public PParameter getParameter()
    {
        return this._parameter_;
    }

    public void setParameter(PParameter node)
    {
        if(this._parameter_ != null)
        {
            this._parameter_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parameter_ = node;
    }

    public LinkedList<PCommaParameter> getCommaParameter()
    {
        return this._commaParameter_;
    }

    public void setCommaParameter(List<?> list)
    {
        for(PCommaParameter e : this._commaParameter_)
        {
            e.parent(null);
        }
        this._commaParameter_.clear();

        for(Object obj_e : list)
        {
            PCommaParameter e = (PCommaParameter) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._commaParameter_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._parameter_)
            + toString(this._commaParameter_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._parameter_ == child)
        {
            this._parameter_ = null;
            return;
        }

        if(this._commaParameter_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._parameter_ == oldChild)
        {
            setParameter((PParameter) newChild);
            return;
        }

        for(ListIterator<PCommaParameter> i = this._commaParameter_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PCommaParameter) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
