/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class APrimaryTypeType extends PType
{
    private PPrimaryType _primaryType_;

    public APrimaryTypeType()
    {
        // Constructor
    }

    public APrimaryTypeType(
        @SuppressWarnings("hiding") PPrimaryType _primaryType_)
    {
        // Constructor
        setPrimaryType(_primaryType_);

    }

    @Override
    public Object clone()
    {
        return new APrimaryTypeType(
            cloneNode(this._primaryType_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPrimaryTypeType(this);
    }

    public PPrimaryType getPrimaryType()
    {
        return this._primaryType_;
    }

    public void setPrimaryType(PPrimaryType node)
    {
        if(this._primaryType_ != null)
        {
            this._primaryType_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._primaryType_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._primaryType_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._primaryType_ == child)
        {
            this._primaryType_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._primaryType_ == oldChild)
        {
            setPrimaryType((PPrimaryType) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
