/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import java.util.*;
import analysis.*;

@SuppressWarnings("nls")
public final class ATerm extends PTerm
{
    private PFactor _factor_;
    private final LinkedList<PMultTerm> _multTerm_ = new LinkedList<PMultTerm>();

    public ATerm()
    {
        // Constructor
    }

    public ATerm(
        @SuppressWarnings("hiding") PFactor _factor_,
        @SuppressWarnings("hiding") List<?> _multTerm_)
    {
        // Constructor
        setFactor(_factor_);

        setMultTerm(_multTerm_);

    }

    @Override
    public Object clone()
    {
        return new ATerm(
            cloneNode(this._factor_),
            cloneList(this._multTerm_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATerm(this);
    }

    public PFactor getFactor()
    {
        return this._factor_;
    }

    public void setFactor(PFactor node)
    {
        if(this._factor_ != null)
        {
            this._factor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._factor_ = node;
    }

    public LinkedList<PMultTerm> getMultTerm()
    {
        return this._multTerm_;
    }

    public void setMultTerm(List<?> list)
    {
        for(PMultTerm e : this._multTerm_)
        {
            e.parent(null);
        }
        this._multTerm_.clear();

        for(Object obj_e : list)
        {
            PMultTerm e = (PMultTerm) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._multTerm_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._factor_)
            + toString(this._multTerm_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._factor_ == child)
        {
            this._factor_ = null;
            return;
        }

        if(this._multTerm_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._factor_ == oldChild)
        {
            setFactor((PFactor) newChild);
            return;
        }

        for(ListIterator<PMultTerm> i = this._multTerm_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PMultTerm) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
