/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import java.util.*;
import analysis.*;

@SuppressWarnings("nls")
public final class AWithVarBegin extends PBegin
{
    private final LinkedList<PParameter> _parameter_ = new LinkedList<PParameter>();
    private TLBrace _lBrace_;
    private PStatements _statements_;
    private TRBrace _rBrace_;

    public AWithVarBegin()
    {
        // Constructor
    }

    public AWithVarBegin(
        @SuppressWarnings("hiding") List<?> _parameter_,
        @SuppressWarnings("hiding") TLBrace _lBrace_,
        @SuppressWarnings("hiding") PStatements _statements_,
        @SuppressWarnings("hiding") TRBrace _rBrace_)
    {
        // Constructor
        setParameter(_parameter_);

        setLBrace(_lBrace_);

        setStatements(_statements_);

        setRBrace(_rBrace_);

    }

    @Override
    public Object clone()
    {
        return new AWithVarBegin(
            cloneList(this._parameter_),
            cloneNode(this._lBrace_),
            cloneNode(this._statements_),
            cloneNode(this._rBrace_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAWithVarBegin(this);
    }

    public LinkedList<PParameter> getParameter()
    {
        return this._parameter_;
    }

    public void setParameter(List<?> list)
    {
        for(PParameter e : this._parameter_)
        {
            e.parent(null);
        }
        this._parameter_.clear();

        for(Object obj_e : list)
        {
            PParameter e = (PParameter) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._parameter_.add(e);
        }
    }

    public TLBrace getLBrace()
    {
        return this._lBrace_;
    }

    public void setLBrace(TLBrace node)
    {
        if(this._lBrace_ != null)
        {
            this._lBrace_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lBrace_ = node;
    }

    public PStatements getStatements()
    {
        return this._statements_;
    }

    public void setStatements(PStatements node)
    {
        if(this._statements_ != null)
        {
            this._statements_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._statements_ = node;
    }

    public TRBrace getRBrace()
    {
        return this._rBrace_;
    }

    public void setRBrace(TRBrace node)
    {
        if(this._rBrace_ != null)
        {
            this._rBrace_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rBrace_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._parameter_)
            + toString(this._lBrace_)
            + toString(this._statements_)
            + toString(this._rBrace_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._parameter_.remove(child))
        {
            return;
        }

        if(this._lBrace_ == child)
        {
            this._lBrace_ = null;
            return;
        }

        if(this._statements_ == child)
        {
            this._statements_ = null;
            return;
        }

        if(this._rBrace_ == child)
        {
            this._rBrace_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PParameter> i = this._parameter_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PParameter) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._lBrace_ == oldChild)
        {
            setLBrace((TLBrace) newChild);
            return;
        }

        if(this._statements_ == oldChild)
        {
            setStatements((PStatements) newChild);
            return;
        }

        if(this._rBrace_ == oldChild)
        {
            setRBrace((TRBrace) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
